use anyhow::Result;

use crate::config::loader;
use crate::envfile::EnvFile;
use crate::wizard::run_wizard;

pub async fn run(reconfigure: bool) -> Result<()> {
    let root = crate::config::locate_root();
    let cfg = loader::load(&root)?;

    let env_path = root.join(".env");
    let existing = EnvFile::load(&env_path)?;

    if reconfigure && !env_path.exists() {
        anyhow::bail!(".env not found — run 'codetainyrrr setup' first");
    }

    let prev = existing.clone();
    let new_env = run_wizard(&cfg.wizard, &cfg.catalog, existing).await?;

    write_env(&new_env, &env_path)?;

    if reconfigure {
        reconcile(&prev, &new_env, &cfg.catalog).await?;
    }

    Ok(())
}

fn write_env(env: &EnvFile, path: &std::path::Path) -> Result<()> {
    let header = "# codetainyrrr configuration\n\
                  # Generated by codetainyrrr setup — edit manually or re-run to update.";
    env.write(path, header)?;
    cliclack::log::success(format!(".env written to {}", path.display()))?;
    Ok(())
}

/// After reconfigure: install newly added tools/plugins, uninstall removed ones.
async fn reconcile(
    old: &EnvFile,
    new: &EnvFile,
    catalog: &crate::config::Catalog,
) -> Result<()> {
    use crate::installer::registry::{self, Kind};

    let old_tools = old.keys_csv("INSTALL_TOOLS");
    let new_tools = new.keys_csv("INSTALL_TOOLS");
    let old_plugins = old.keys_csv("INSTALL_PLUGINS");
    let new_plugins = new.keys_csv("INSTALL_PLUGINS");

    // Install added tools
    for key in new_tools.iter().filter(|k| !old_tools.contains(k)) {
        if let Some(tool) = catalog.tools.iter().find(|t| &t.key == key) {
            if let Some(spec) = &tool.install {
                cliclack::log::info(format!("installing tool: {key}"))?;
                registry::install(Kind::Tool, key, spec).await?;
            }
        }
    }
    // Uninstall removed tools
    for key in old_tools.iter().filter(|k| !new_tools.contains(k)) {
        if let Some(tool) = catalog.tools.iter().find(|t| &t.key == key) {
            if let Some(spec) = &tool.install {
                cliclack::log::info(format!("removing tool: {key}"))?;
                registry::uninstall(Kind::Tool, key, spec).await?;
            }
        }
    }

    // Install added plugins
    for key in new_plugins.iter().filter(|k| !old_plugins.contains(k)) {
        if let Some(plugin) = catalog.plugins.iter().find(|p| &p.key == key) {
            if let Some(spec) = &plugin.install {
                cliclack::log::info(format!("installing plugin: {key}"))?;
                registry::install(Kind::Plugin, key, spec).await?;
            }
        }
    }
    // Uninstall removed plugins
    for key in old_plugins.iter().filter(|k| !new_plugins.contains(k)) {
        if let Some(plugin) = catalog.plugins.iter().find(|p| &p.key == key) {
            if let Some(spec) = &plugin.install {
                cliclack::log::info(format!("removing plugin: {key}"))?;
                registry::uninstall(Kind::Plugin, key, spec).await?;
            }
        }
    }

    Ok(())
}
