use anyhow::Result;

use crate::config::loader;
use crate::envfile::EnvFile;
use crate::wizard::run_wizard;

pub async fn run(reconfigure: bool) -> Result<()> {
    let root = crate::config::locate_root();
    let cfg = loader::load(&root)?;

    let env_path = root.join(".env");
    let existing = EnvFile::load(&env_path)?;

    if reconfigure && !env_path.exists() {
        anyhow::bail!(
            ".env not found — run '{} setup' first",
            cfg.catalog.project.binary_name
        );
    }

    let prev = existing.clone();
    let new_env = run_wizard(&cfg.wizard, &cfg.catalog, existing).await?;

    write_env(&new_env, &env_path, &cfg.catalog.project)?;

    if reconfigure {
        reconcile(&prev, &new_env, &cfg.catalog).await?;
    }

    // Offer to start the container immediately so the new .env takes effect.
    // Skipped when stdin isn't a terminal (CI / piped runs) so scripts don't
    // hang waiting for input.
    if std::io::IsTerminal::is_terminal(&std::io::stdin()) {
        let bin = &cfg.catalog.project.binary_name;
        let start: bool = cliclack::confirm(format!("Start the container now? (runs `{bin} run`)"))
            .initial_value(true)
            .interact()
            .unwrap_or(false);
        if start {
            return crate::cmd::run::run(false, vec![]).await;
        }
        cliclack::log::info(format!("Done. Run `{bin} run` when ready."))?;
    }

    Ok(())
}

fn write_env(
    env: &EnvFile,
    path: &std::path::Path,
    project: &crate::config::ProjectMeta,
) -> Result<()> {
    let header = format!(
        "{}\n# Generated by {} setup — edit manually or re-run to update.",
        project.env_header, project.binary_name
    );
    env.write(path, &header)?;
    cliclack::log::success(format!(".env written to {}", path.display()))?;
    Ok(())
}

/// After reconfigure: install newly added tools/plugins (with dependencies and
/// post_install hooks via the orchestrator), uninstall removed ones.
async fn reconcile(old: &EnvFile, new: &EnvFile, catalog: &crate::config::Catalog) -> Result<()> {
    use crate::installer::orchestrator;
    use crate::installer::registry::{self, Kind};

    let old_tools = old.keys_csv("INSTALL_TOOLS");
    let new_tools = new.keys_csv("INSTALL_TOOLS");
    let old_plugins = old.keys_csv("INSTALL_PLUGINS");
    let new_plugins = new.keys_csv("INSTALL_PLUGINS");

    // Install everything that's new (orchestrator handles deps + post_install).
    let added: Vec<String> = new_tools
        .iter()
        .chain(new_plugins.iter())
        .filter(|k| !old_tools.contains(k) && !old_plugins.contains(k))
        .cloned()
        .collect();
    if !added.is_empty() {
        cliclack::log::info(format!("installing: {}", added.join(", ")))?;
        let summary = orchestrator::install_many(catalog, &added).await;
        if !summary.failed.is_empty() {
            cliclack::log::warning(format!(
                "{} install(s) failed: {}",
                summary.failed.len(),
                summary
                    .failed
                    .iter()
                    .map(|(k, _)| k.as_str())
                    .collect::<Vec<_>>()
                    .join(", ")
            ))?;
            for (k, err) in &summary.failed {
                let first = err.lines().next().unwrap_or("");
                cliclack::log::warning(format!("  {k}: {first}"))?;
            }
        }
    }

    // Uninstalls remain direct since they have no dep ordering concerns.
    for key in old_tools.iter().filter(|k| !new_tools.contains(k)) {
        if let Some(tool) = catalog.tools.iter().find(|t| &t.key == key)
            && let Some(spec) = &tool.install
        {
            cliclack::log::info(format!("removing tool: {key}"))?;
            registry::uninstall(Kind::Tool, key, spec).await?;
        }
    }
    for key in old_plugins.iter().filter(|k| !new_plugins.contains(k)) {
        if let Some(plugin) = catalog.plugins.iter().find(|p| &p.key == key)
            && let Some(spec) = &plugin.install
        {
            cliclack::log::info(format!("removing plugin: {key}"))?;
            registry::uninstall(Kind::Plugin, key, spec).await?;
        }
    }

    Ok(())
}
